# $Id$
#
# opt_rpl module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=ifctools.so
LIBS=

include ../../Makefile.modules
